query doodles(
  $offset: Int
  $searchText: String
  $order: QueryOrder
  $type: String
  $countries: [String!]
  $tags: [String!]
  $startDate: String
  $endDate: String
) {
  doodles(
    limit: 4
    offset: $offset
    order: $order

    searchText: $searchText

    type: $type
    countries: $countries
    tags: $tags

    startDate: $startDate
    endDate: $endDate
  ) {
    id
    title
    url
  }
}

query historyDoodles($month: Int!, $day: Int!) {
  historyDoodles(month: $month, day: $day) {
    id
    title
    url
  }
}

query filters {
  filters {
    types
    countries
    tags
  }
}
