scalar Date

enum QueryOrder {
  Latest
  Oldest
}

type Filters {
  types: [DoodleType!]!
  countries: [String!]!
  tags: [String!]!
}

type Query {
  filters: Filters!

  historyDoodles(month: Int!, day: Int!): [Doodle!]!

  doodles(
    limit: Int
    offset: Int
    order: QueryOrder

    searchText: String

    type: String
    countries: [String!]
    tags: [String!]

    startDate: String # YYYY-MM-DD
    endDate: String # YYYY-MM-DD
  ): [Doodle!]!
}
